config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :authors
  root 'home#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_author!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Homepage!</h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Blog", root_path, class:"navbar-brand" %>
        </li>
        <% if author_signed_in? %>
          <li class="nav-item">
            <%= button_to "Sign Out", destroy_author_session_path, method: :delete, data: { turbo: false }, class:"btn btn-outline-danger" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Register", new_author_registration_path, class:"navbar-brand" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_author_session_path, class:"navbar-brand" %>
          </li>
        <% end %>
      </ul>
      <% if author_signed_in? %>
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <span class="navbar-text">
            <%= "Hi #{current_author.email}!" %>
          </span>
        </ul>
      <% end %>
      <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
        <% if author_signed_in? %>
          <li class="nav-item">
            <%=link_to "Account settings", edit_author_registration_path, class:"navbar-brand" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>
  </body>
</html>